### PR TITLE
this is the week2

### PR DESCRIPTION
**Pull request by Zion-7**
Nameable Interface:

Defines the Nameable interface with a single method correctName().
The correctName() method is intended to be implemented by classes that need to provide a corrected or formatted version of a name.
Person Class:

Represents an individual with attributes such as id, name, and age.
Implements the Nameable interface, providing an implementation for the correct Name() method by returning the person's name.
Includes a constructor for initializing the person's attributes.
Can be used to create instances of individuals with associated information.
Decorator Class:

Serves as a base class for decorators implementing the Nameable interface.
Contains a reference to a Nameable object that it decorates.
Implements the correct Name() method, delegating the call to the wrapped Nameable object.
Capitalize Decorator Class:

Extends the Decorator class.
Overrides the correct Name() method to capitalize the output of the wrapped Nameable object.
Trimmer Decorator Class:

Extends the Decorator class.
Overrides the correct Name() method to limit the output of the wrapped Nameable object to a maximum of 10 characters by trimming if necessary.

### CODE REVIEW

**Review by Benawi — CHANGES_REQUESTED** [review]
Hi 👋 @Zion-7 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

  - Person, Teacher, and student classes are missed in this branch
 
giphy

Your Code Review Request will be marked as invalid, so please submit a new one once you are ready 🙏


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @benawi in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by Benawi — CHANGES_REQUESTED** [review]
Hi, @Zion-7 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



## Highlights
❌ Correct use of Gitflow
✅ Create a class ` Nameable` --- Interface
✅ `Person ` class inherits from `Nameable`
✅ Create `Decorator ` and inherits from `Nameable`.
✅ Create ` CapitalizeDecorator ` and ` TrimmerDecorator`


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @benawi in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

**Comment by bayekido** [comment]
Sir already you have approved my project then I got commit from you, but
when I tried to merge it to development branch then I got error
that asked me to resolve conflict, and I resolved it and saved file and
merge it, finally you said it is not correct git flow so review my code and
tell me what I have to do clearly on code ,,,,

**Comment by Benawi** [comment]
- You confuse me    @bayekido,   about which repo you are talking , Please can you make it clear
-image

**Pull request merged**
